# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e989f1758a90b03f9092b079a25d0f141199e0fa4e4b987b9a4d0f67d1139f39cdec30349c1a2d96438a9cac6a57b14d6eaa7c1f4715f1f0782e2428e23deae

test:
  secret_key_base: 70295bdcd4ca070632b806e8f24c0df35cf700ad8149391ea6a70df556db1fb009a5f25455b03c1d806c126cca1e99ba2418eb4eb78014f36b1d25f4afa0d615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
